### ISSUE TITLE
Missing train.txt and val.txt file

### ISSUE THREAD

**Issue by zuoym15** [yshen47/SGAM_NeurIPS22#1]
Hi,

Thanks for presenting the great work! 
I'm trying to reproduce your training on the CLEVR dataset you provided. I ran the VGGAN codebook training step but seems it  needs a train.txt and a val.txt file ([here](https://github.com/yshen47/SGAM/blob/8642678e4c974c48a4b7220b827d66a7f8182bca/data/utils/utils.py#L253)). Would you please tell me where can I find the file or how can I generate it?
Thanks a lot!

**Comment by yshen47** [comment]
Hey there,
[val.txt](https://github.com/yshen47/SGAM/files/10703381/val.txt)
[train.txt](https://github.com/yshen47/SGAM/files/10703382/train.txt)

Thanks for interest for trying out! Here is the train and val.txt
