### ISSUE TITLE
The image resolutions are not consistent in data loaders and configs

### ISSUE THREAD

**Issue by hzxie** [yshen47/SGAM_NeurIPS22#2]
In the config file, the image resolution is 256x256.

https://github.com/yshen47/SGAM/blob/d02768c2fa0084d1144dbebc84e14e50e895243a/trained_models/google_earth/config.yaml#L73-L75

However, in the data loader, the image resolution is 512x512.

https://github.com/yshen47/SGAM/blob/d02768c2fa0084d1144dbebc84e14e50e895243a/data/google_earth.py#L50-L51

**Comment by hzxie** [comment]
BTW, if an image is rescaled to 256x256.
The values in K should be:

```
    scale_x = 256 / self.image_resolution[1]
    scale_y = 256 / self.image_resolution[0]
    self.K[0] = self.K[0] * scale_x
    self.K[1] = self.K[1] * scale_y
```

However, in the released code, the K values are computed by

```
    self.K[0] = self.K[0] / scale_x
    self.K[1] = self.K[1] / scale_y
```

I think it would lead to the wrong result.
Ref: https://dsp.stackexchange.com/a/6057

**Comment by yshen47** [comment]
Hi there,
Thanks for digging into our codebase! To clarify, the released checkpoint is trained on 256x256 images. however we use a different checkpoint on 512 x 512 (not released), when presenting number in our paper. Hope it helps!

Yuan

**Comment by hzxie** [comment]
Is it possible to release the checkpoint on 512x512?
How about the second question? The calculation of K may not be correct.

**Comment by yshen47** [comment]
Unfortunately, we are not release the checkpoint on 512 x 512. For the second question, you are right, it should be divided by 256 instead of 512, I guess some commit version might mess up. Thanks!

**Comment by hzxie** [comment]
Thanks for your reply.
